config:
  modelConfig:
    DataObject:
      operations:
        read:
          plugins:
            sort: true
        readOne:
          plugins:
            getByLink:
              after: filter
